/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LausanneRouteImport } from './routes/lausanne'
import { Route as IndexRouteImport } from './routes/index'

const LausanneRoute = LausanneRouteImport.update({
  id: '/lausanne',
  path: '/lausanne',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/lausanne': typeof LausanneRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/lausanne': typeof LausanneRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/lausanne': typeof LausanneRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/lausanne'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/lausanne'
  id: '__root__' | '/' | '/lausanne'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LausanneRoute: typeof LausanneRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/lausanne': {
      id: '/lausanne'
      path: '/lausanne'
      fullPath: '/lausanne'
      preLoaderRoute: typeof LausanneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LausanneRoute: LausanneRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
